# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import pages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'db_table': 'Предмет',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание страницы')),
                ('title', models.CharField(max_length=250, verbose_name='Название акции')),
                ('img', models.FileField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Главное Изображение')),
                ('image', models.FileField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение')),
                ('image_1', models.FileField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение')),
                ('image_2', models.FileField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение')),
                ('image_3', models.FileField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Параграф')),
                ('slug', models.SlugField(blank=True, help_text='К примеру, "new-share-for_2018"', max_length=150, null=True, validators=[pages.validators.validate_slug_field], verbose_name='Название ссылки к странице акции')),
                ('additional_text', models.TextField(blank=True, max_length=16384, null=True, verbose_name='Контент')),
                ('announce', models.TextField(blank=True, max_length=560, null=True, verbose_name='Анонс акции')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-published_date'],
            },
        ),
    ]
