# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='additional_text',
        ),
        migrations.RemoveField(
            model_name='share',
            name='created_date',
        ),
        migrations.AddField(
            model_name='share',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='share',
            name='text',
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name='Контент'),
        ),
    ]
