# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:12
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20180314_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='image_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='image_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Главное Изображение'),
        ),
    ]
